services:
  fake-gcs-server:
    image: fsouza/fake-gcs-server:1.54.0
    ports:
      - 8080:8080
    networks:
      - discovery-network
    volumes:
      - fake-gcs-data:/storage
    command:
      [
        "-scheme",
        "http",
        "-port",
        "8080",
        "-external-url",
        "http://fake-gcs-server:8080",
        "-public-host",
        "fake-gcs-server",
        "-backend",
        "filesystem",
        "-filesystem-root",
        "/storage",
      ]
  mongo:
    attach: false
    image: mongo:8.0
    ports:
      - 27017:27017
    networks:
      - discovery-network
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend.dev
      target: backend-dev
    volumes:
      - type: bind
        source: ./apps/backend
        target: /app/apps/backend
    environment:
      NODE_ENV: development
      DB_HOST: mongo
      DB_PORT: 27017
      DB_NAME: offbeat-fm-dev
      PORT: 3001
      CLIENT_URL: http://localhost:3000
      CLIENT_URLS: http://localhost:3000, http://admin.localhost:3000
    ports:
      - 3001:3001
    networks:
      - discovery-network
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    secrets:
      - SESSION_SECRET
      - RESEND_API_KEY
    develop:
      watch:
        - path: ./common/types/src
          action: rebuild
        - path: ./common/validation/src
          action: rebuild
        - path: ./common/json-data/src
          action: rebuild

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.dev
    develop:
      watch:
        - path: ./components/src
          action: rebuild
        - path: ./common/types/src
          action: rebuild
        - path: ./common/validation/src
          action: rebuild
        - path: ./common/json-data/src
          action: rebuild
    volumes:
      - type: bind
        source: ./apps/frontend
        target: /app/apps/frontend

    environment:
      NODE_ENV: development
      BACKEND_URL: http://backend:3001/api/v1
    ports:
      - 3000:3000
    networks:
      - discovery-network
    depends_on:
      - backend
secrets:
  SESSION_SECRET:
    file: ./secrets/SESSION_SECRET.txt
  RESEND_API_KEY:
    file: ./secrets/RESEND_API_KEY.txt

networks: # allow services to talk to each other while providing isolation from other docker container, running on the same host
  discovery-network:
    driver: bridge

volumes: # enable persistence of database data across container restart
  mongo-data:
    driver: local
  fake-gcs-data:
    driver: local
