# syntax=docker/dockerfile:1
# check=error=true;experimental=CopyIgnoredFile

ARG NODE_VERSION=24.4.0
FROM node:${NODE_VERSION}-alpine AS backend-base

WORKDIR /app

COPY package.json yarn.lock tsconfig.json .yarnrc.yml ./
COPY apps/backend/package.json apps/backend/tsconfig.json ./apps/backend/
COPY apps/backend/src/ ./apps/backend/src/
COPY apps/backend/test-helpers/ ./apps/backend/test-helpers/
COPY common/types/package.json common/types/tsconfig.json ./common/types/
COPY common/types/src/ ./common/types/src/
COPY common/json-data/package.json common/json-data/tsconfig.json ./common/json-data/
COPY common/json-data/src/ ./common/json-data/src/
COPY common/validation/package.json common/validation/tsconfig.json ./common/validation/
COPY common/validation/src/ ./common/validation/src/
RUN corepack enable && yarn install

FROM backend-base AS backend-build
WORKDIR /app
COPY --from=backend-base /app/node_modules ./node_modules
RUN yarn workspace @common/json-data build
RUN yarn workspace @common/types build
RUN yarn workspace @common/validation build

FROM backend-build AS backend-test
WORKDIR /app
COPY --from=backend-build /app ./
CMD [ "yarn", "workspace", "backend", "test" ]

FROM backend-base AS backend-dev
RUN addgroup -g 1225 backend-group && \
    adduser -S -u 1225 -g backend-group backend-user
RUN chown -R backend-user:backend-group /app
    
USER backend-user

WORKDIR /app
COPY --from=backend-build /app ./
# RUN corepack enable && yarn install
ENV CLIENT_URL=http://localhost:3000
# ENV SESSION_SECRET=testing_secret
EXPOSE 3001

CMD [ "yarn", "workspace", "backend", "dev" ]
