# syntax=docker/dockerfile:1
# check=error=true;experimental=CopyIgnoredFile

ARG NODE_VERSION=24.4.0
FROM node:${NODE_VERSION}-alpine AS base
WORKDIR /app
# RUN apt-get update && apt-get install -y shadow-utils

FROM base AS frontend-dependencies
WORKDIR /app

COPY package.json yarn.lock tsconfig.json .yarnrc.yml ./

COPY components/package.json \
components/tsconfig.json \
components/postcss.config.mjs \
./components/

COPY common/types/package.json \
common/types/tsconfig.json \
./common/types/

COPY common/json-data/package.json \
common/json-data/tsconfig.json \
./common/json-data/

COPY common/validation/package.json \
common/validation/tsconfig.json \
./common/validation/

COPY apps/frontend/package.json \
apps/frontend/tsconfig.json \
apps/frontend/postcss.config.mjs \
apps/frontend/next.config.ts \
apps/frontend/next.config.ts \
apps/frontend/next-env.d.ts \
./apps/frontend/

RUN corepack enable && yarn install
CMD ["tail", "-f", "/dev/null"]


# COPY apps/frontend/actions/ ./apps/frontend/actions/
# COPY apps/frontend/app/ ./apps/frontend/app/
# COPY apps/frontend/lib/ ./apps/frontend/lib/

# COPY common/types/src/ ./common/types/src/

# COPY components/src/ ./components/src/

FROM base AS frontend-build
WORKDIR /app

COPY --from=frontend-dependencies /app/.yarn ./.yarn
COPY --from=frontend-dependencies /app/.yarnrc.yml ./.yarnrc.yml
COPY --from=frontend-dependencies /app/node_modules ./node_modules

COPY --from=frontend-dependencies \
/app/package.json \
/app/yarn.lock \
/app/tsconfig.json \
./

# Copy frontend source files
COPY apps/frontend/ \
/app/apps/frontend/

# Copy component source files
COPY \
components/ \
/app/components/

COPY \
common/types/ \
./common/types/

COPY \
common/json-data/ \
./common/json-data/

COPY \
common/validation/ \
./common/validation/
RUN corepack enable

RUN yarn workspace @common/json-data build
RUN yarn workspace @common/types build
RUN yarn workspace @common/validation build
RUN yarn workspace @mda/components build
CMD ["tail", "-f", "/dev/null"]

FROM base AS frontend-test
WORKDIR /app
COPY --from=frontend-build /app ./
RUN corepack enable
ENV NODE_ENV=test
CMD [ "yarn", "workspace", "frontend", "test" ]

FROM base AS frontend-dev
RUN addgroup -g 1224 nextjs-group && \
    adduser -S -u 1224 -g nextjs-group nextjs-user
RUN chown -R nextjs-user:nextjs-group /app
    

WORKDIR /app
COPY --from=frontend-build /app ./
RUN corepack enable
USER nextjs-user

EXPOSE 3000

CMD [ "yarn", "workspace", "frontend", "dev" ]
